[package]
name = "find_dups"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.1", features = ["derive"] }
kurbo = "0.11.0"
skrifa = "0.15.5"
write-fonts = "0.21.0"  # pens
